# Generated by Django 5.1.2 on 2024-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('c_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('rank', models.IntegerField()),
                ('c_rank', models.IntegerField()),
                ('xii_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
