# Generated by Django 5.1.2 on 2024-10-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=15, unique=True)),
                ('c_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('rank', models.IntegerField()),
                ('c_rank', models.IntegerField()),
                ('xii_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
